config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers

  namespace :admins do
    resources :dashboard
    resources :products
    resources :orders
    resources :stockes
    resources :categories
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def address
    "#{city}, #{state}, #{country}"
  end       
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admins_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to admins_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admins_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/admins/dashboard_controller.rb
class Admins::DashboardController < ApplicationController
  def index
    @categories = Category.all.count
    @products = Product.all.count
    @orders = Order.all
    @total_revenew = @orders.includes(:product)
    @profit = []
    @total_revenew.each do |price|
      @profit << price.product.sell_price - price.product.purchase_price
    end
  end
end

app/controllers/admins/orders_controller.rb
class  Admins::OrdersController < ApplicationController
  def index
    @orders = Order.includes(:customer).all
  end  
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
  def index
    @products = Product.all
  end  

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admins_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admins_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admins_products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :purchase_price, :sell_price, :category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/_header.html.haml
%body
  %header.header-wrap
    .container
      .row
        .menu-item-wap
          %ul
            %li
              = link_to "Dashboard", admins_dashboard_index_path
            %li
              = link_to "Categories", admins_categories_path
            %li
              = link_to "Products", admins_products_path
            %li
              = link_to "Orders", admins_orders_path

app/views/admins/categories/_form.html.haml
= form_with model: [:admins, category] do |form|
  %div
    = form.label :name
    %br
    = form.text_field :name
  %br
  %div
    = form.label :description
    %br
    = form.text_area :description
    %br
  %br
  %div
    = form.submit

app/views/admins/categories/edit.html.haml
= render partial: 'admins/header'
%h1 Edit Category
%br
= render "form", category: @category

app/views/admins/categories/index.html.haml
= render partial: 'admins/header'

%h1= "All Category"
%br
%brss

%table
  %thead
    %tr
      %th ID
      %th Name  
      %th{colspan: "2"} Action
  %tbody
    - @categories.each do |category|
      %tr
        %td= category.id
        %td= category.name
        %td
          = link_to edit_admins_category_path(category) do
            edit
        %td
          = link_to admins_category_path(category), method: 'delete', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do
            Delete
%br
%br
= link_to new_admins_category_path do
  Add

app/views/admins/categories/new.html.haml
= render partial: 'admins/header'
%h2 Create Category
%br
= render "form", category: @category

app/views/admins/dashboard/index.html.haml
= render partial: 'admins/header'
%main
  %section.card-wrap
    .container
      .row
        .card-box-text
          %h1 Dashboard
        .card-box
          .card-box-item
            %h2= @categories
            %h4 Categories
          .card-box-item
            %h2= @products
            %h4 Products
          .card-box-item
            %h2= @orders.count
            %h4 Total Order
          .card-box-item
            %h2(style="color: green;")= @profit.sum
            %h4 Profit

app/views/admins/orders/index.html.haml
= render partial: 'admins/header'

%h1 All Orders
%br
%br
%table
  %thead
    %tr
      %th ID
      %th Customer Name
      %th Address
      %th Mobile
      %th Product Name 
      %th Price
  %tbody
    - @orders.each do |order|
      %tr
        %td= order.id
        %td= order.customer.name
        %td= order.customer.address
        %td= order.customer.mobile
        %td= order.product.name
        %td= order.product.sell_price
       

app/views/admins/products/_form.html.haml
= form_with model: [:admins, product] do |form|
  %div
    = form.label :name
    %br
    = form.text_field :name
  %br
  %div
    = form.label :purchase_price
    %br
    = form.text_field :purchase_price
  %br
  %div 
    = form.label :sell_price
    %br
    = form.text_field :sell_price
  %br
  %div
    = form.label :category
    = form.collection_select(:category_id, @categories, :id, :name, prompt: 'Select a category')
  %br
  = form.submit 'Create Product'

app/views/admins/products/edit.html.haml
= render partial: 'admins/header'
%h1 Edit Product
%br
%br
= render "form", product: @product

app/views/admins/products/index.html.haml
= render partial: 'admins/header'

%h1 All Products
%br
%br
%table
  %thead
    %tr
      %th ID
      %th Name
      %th Purchase Price
      %th Sell Price  
      %th Category
      %th{colspan: "2"} Action
  %tbody
    - @products.each do |product|
      %tr
        %td= product.id
        %td= product.name
        %td= product.purchase_price
        %td= product.sell_price
        %td= product.category.name
        %td
          = link_to edit_admins_product_path(product) do
            edit
        %td
          = link_to admins_product_path(product), method: 'delete', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do
            Delete
%br
= link_to new_admins_product_path do
  Add

app/views/admins/products/new.html.haml
= render partial: 'admins/header'
%h1 Create Product
%br
%br
= render "form", product: @product

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minecartshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>